### ISSUE TITLE
error handling doesn't match decimal.js

### ISSUE THREAD

**Issue by erosson** [Patashu/break_infinity.js#18]
> var Decimal = require('decimal.js')
    undefined
    > var BDecimal = require('break_infinity.js/break_infinity.js')
    undefined
    > new Decimal('fail')
    Error: [DecimalError] Invalid argument: fail
        at parseOther (/home/evan/code/swarm-numberformat/node_modules/decimal.js/decimal.js:3596:13)
        at new Decimal (/home/evan/code/swarm-numberformat/node_modules/decimal.js/decimal.js:4298:55)
        at repl:1:1
        at ContextifyScript.Script.runInThisContext (vm.js:50:33)
        at REPLServer.defaultEval (repl.js:240:29)
        at bound (domain.js:301:14)
        at REPLServer.runBound [as eval] (domain.js:314:12)
        at REPLServer.onLine (repl.js:441:10)
        at emitOne (events.js:121:20)
        at REPLServer.emit (events.js:211:7)
    > new BDecimal('fail')
    Decimal { mantissa: NaN, exponent: NaN }

I expected them to behave the same, but decimal.js throws an error while break_infinity returns NaN.

**Comment by Patashu** [comment]
This is not normally something I'd consider a bug, but if it breaks Swarm Simulator I'll fix it.

**Comment by Patashu** [comment]
Committed. Let me know if you need error handling on any other cases. Note that in decimal.js, new Decimal("NaN") does return a NaN, so it does here too.

**Comment by Patashu** [comment]
Closing this one for now, feel free to re-open if needed
